# Generated by Django 5.2.3 on 2025-08-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.employe')),
            ],
        ),
    ]
