# Generated by Django 5.2.3 on 2025-08-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_versement', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.employe')),
            ],
        ),
    ]
