# Generated by Django 5.2.3 on 2025-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('organisme', models.CharField(max_length=100)),
                ('employes', models.ManyToManyField(related_name='formations', to='personnel.employe')),
            ],
        ),
    ]
